// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteSetup() {
  return window['go']['main']['App']['CompleteSetup']();
}

export function GetChannelStatus() {
  return window['go']['main']['App']['GetChannelStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetInstalledSkills() {
  return window['go']['main']['App']['GetInstalledSkills']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetMemStats() {
  return window['go']['main']['App']['GetMemStats']();
}

export function IsSetupCompleted() {
  return window['go']['main']['App']['IsSetupCompleted']();
}

export function SaveBrowserConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveBrowserConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveLLMConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveLLMConfig'](arg1, arg2, arg3, arg4);
}

export function SavePluginsConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SavePluginsConfig'](arg1, arg2, arg3, arg4);
}

export function SaveSecurityConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveSecurityConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveTelegramConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveTelegramConfig'](arg1, arg2);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function TestLLMConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestLLMConnection'](arg1, arg2, arg3, arg4);
}

export function TestTelegramConnection(arg1) {
  return window['go']['main']['App']['TestTelegramConnection'](arg1);
}
