// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {skill} from '../models';
import {main} from '../models';

export function CompleteSetup():Promise<void>;

export function GetChannelStatus():Promise<Record<string, boolean>>;

export function GetConfig():Promise<Record<string, any>>;

export function GetInstalledSkills():Promise<Array<skill.SkillInfo>>;

export function GetLogs():Promise<Array<main.LogEntry>>;

export function GetMemStats():Promise<Record<string, any>>;

export function IsSetupCompleted():Promise<boolean>;

export function SaveBrowserConfig(arg1:boolean,arg2:boolean,arg3:number,arg4:number,arg5:string,arg6:string):Promise<void>;

export function SaveLLMConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SavePluginsConfig(arg1:boolean,arg2:Array<string>,arg3:number,arg4:boolean):Promise<void>;

export function SaveSecurityConfig(arg1:boolean,arg2:boolean,arg3:boolean,arg4:boolean,arg5:boolean,arg6:boolean):Promise<void>;

export function SaveTelegramConfig(arg1:string,arg2:Array<number>):Promise<void>;

export function SendMessage(arg1:string):Promise<string>;

export function TestLLMConnection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function TestTelegramConnection(arg1:string):Promise<string>;
